/* Generated by the Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI146048 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI4262 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI148769 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26395 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26391 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26387 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26383 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26379 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26375 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26371 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26367 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26363 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26359 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26355 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26351 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26347 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26343 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26339 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26335 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26331 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26327 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26323 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26319 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI26204 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26262 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26260 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26218 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI26452 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26450 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26220 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26448 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26222 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26248 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26246 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26499 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26542 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI26254 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26252 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI130 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI26216 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26214 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI26230 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI26228 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI28057 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI4250 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4258 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI104 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI16344 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI4208 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4318 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI114 = {size: 0,kind: 40,base: null,node: null,finalizer: null};
var NTI138 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI140 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI4312 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI4226 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4228 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4242 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI4246 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI4246 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4246.node = NNI4246;
var NNI4242 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4242.node = NNI4242;
var NNI4228 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4228.node = NNI4228;
NTI4312.base = NTI4226;
NTI4318.base = NTI4226;
var NNI4226 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI4312, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI140, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI138, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI138, name: "trace", sons: null}, 
{kind: 1, offset: "raiseId", len: 0, typ: NTI114, name: "raiseId", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI4318, name: "up", sons: null}]};
NTI4226.node = NNI4226;
var NNI4208 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4208.node = NNI4208;
NTI4226.base = NTI4208;
NTI4228.base = NTI4226;
NTI4242.base = NTI4228;
NTI4246.base = NTI4242;
var NNI16344 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI140, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI104, name: "Field1", sons: null}]};
NTI16344.node = NNI16344;
var NNI4258 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4258.node = NNI4258;
NTI4258.base = NTI4228;
var NNI4250 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4250.node = NNI4250;
NTI4250.base = NTI4228;
var NNI26216 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI26216.node = NNI26216;
NTI26216.base = NTI4208;
NTI26214.base = NTI26216;
NTI26542.base = NTI26228;
var NNI26254 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "action", len: 0, typ: NTI140, name: "action", sons: null}, 
{kind: 1, offset: "encoding", len: 0, typ: NTI140, name: "encoding", sons: null}, 
{kind: 1, offset: "method", len: 0, typ: NTI140, name: "method", sons: null}, 
{kind: 1, offset: "target", len: 0, typ: NTI140, name: "target", sons: null}, 
{kind: 1, offset: "elements", len: 0, typ: NTI26542, name: "elements", sons: null}]};
NTI26254.node = NNI26254;
NTI26254.base = NTI26230;
NTI26252.base = NTI26254;
var NNI26248 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "defaultSelected", len: 0, typ: NTI130, name: "defaultSelected", sons: null}, 
{kind: 1, offset: "selected", len: 0, typ: NTI130, name: "selected", sons: null}, 
{kind: 1, offset: "selectedIndex", len: 0, typ: NTI104, name: "selectedIndex", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI140, name: "text", sons: null}, 
{kind: 1, offset: "value", len: 0, typ: NTI140, name: "value", sons: null}]};
NTI26248.node = NNI26248;
NTI26248.base = NTI26230;
NTI26246.base = NTI26248;
NTI26499.base = NTI26246;
var NNI26230 = {kind: 2, len: 11, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "classList", len: 0, typ: NTI26214, name: "classList", sons: null}, 
{kind: 1, offset: "checked", len: 0, typ: NTI130, name: "checked", sons: null}, 
{kind: 1, offset: "defaultChecked", len: 0, typ: NTI130, name: "defaultChecked", sons: null}, 
{kind: 1, offset: "defaultValue", len: 0, typ: NTI140, name: "defaultValue", sons: null}, 
{kind: 1, offset: "disabled", len: 0, typ: NTI130, name: "disabled", sons: null}, 
{kind: 1, offset: "form", len: 0, typ: NTI26252, name: "form", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI140, name: "name", sons: null}, 
{kind: 1, offset: "readOnly", len: 0, typ: NTI130, name: "readOnly", sons: null}, 
{kind: 1, offset: "options", len: 0, typ: NTI26499, name: "options", sons: null}, 
{kind: 1, offset: "clientWidth", len: 0, typ: NTI104, name: "clientWidth", sons: null}, 
{kind: 1, offset: "clientHeight", len: 0, typ: NTI104, name: "clientHeight", sons: null}]};
NTI26230.node = NNI26230;
NTI26220.base = NTI26222;
NTI26448.base = NTI26220;
NTI26450.base = NTI26220;
NTI26452.base = NTI26220;
var NNI26218 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI26218, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI26218, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI26218, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI26218, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI26218, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI26218, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI26218, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI26218, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI26218, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI26218, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI26218, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI26218, name: "NotationNode", len: 0, sons: null}}};
NTI26218.node = NNI26218;
var NNI26262 = {kind: 2, len: 91, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "background", len: 0, typ: NTI140, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI140, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI140, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI140, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI140, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI140, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI140, name: "border", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI140, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI140, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI140, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI140, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI140, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI140, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI140, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI140, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI140, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI140, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI140, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI140, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI140, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI140, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI140, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI140, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI140, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI140, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI140, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI140, name: "bottom", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI140, name: "captionSide", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI140, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI140, name: "clip", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI140, name: "color", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI140, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI140, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI140, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI140, name: "emptyCells", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI140, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI140, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI140, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI140, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI140, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI140, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI140, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI140, name: "fontWeight", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI140, name: "height", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI140, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI140, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI140, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI140, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI140, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI140, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI140, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI140, name: "margin", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI140, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI140, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI140, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI140, name: "marginTop", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI140, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI140, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI140, name: "minHeight", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI140, name: "minWidth", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI140, name: "overflow", sons: null}, 
{kind: 1, offset: "overflowX", len: 0, typ: NTI140, name: "overflowX", sons: null}, 
{kind: 1, offset: "overflowY", len: 0, typ: NTI140, name: "overflowY", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI140, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI140, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI140, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI140, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI140, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI140, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI140, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI140, name: "position", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI140, name: "right", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI140, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI140, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI140, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI140, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI140, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI140, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI140, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI140, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI140, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI140, name: "textAlign", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI140, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI140, name: "textIndent", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI140, name: "textTransform", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI140, name: "top", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI140, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI140, name: "visibility", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI140, name: "width", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI140, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI104, name: "zIndex", sons: null}]};
NTI26262.node = NNI26262;
NTI26262.base = NTI4208;
NTI26260.base = NTI26262;
var NNI26222 = {kind: 2, len: 14, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI26448, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI26450, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI26452, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI140, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI26220, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI26220, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI26220, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI140, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI26218, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI140, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI26220, name: "parentNode", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI26220, name: "previousSibling", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI140, name: "innerHTML", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI26260, name: "style", sons: null}]};
NTI26222.node = NNI26222;
var NNI26204 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI26319, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI26323, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI26327, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI26331, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI26335, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI26339, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI26343, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI26347, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI26351, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI26355, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI26359, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI26363, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI26367, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI26371, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI26375, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI26379, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI26383, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI26387, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI26391, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI26395, name: "onunload", sons: null}]};
NTI26204.node = NNI26204;
NTI26204.base = NTI4208;
NTI26222.base = NTI26204;
NTI26230.base = NTI26222;
NTI26228.base = NTI26230;
NTI28057.base = NTI26228;
NTI148769.base = NTI140;
var NNI4262 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI4262.node = NNI4262;
NTI4262.base = NTI4228;
var NNI146048 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI104, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI130, name: "Field1", sons: null}]};
NTI146048.node = NNI146048;

function makeNimstrLit(c_17212) {
		  var ln = c_17212.length;
  var result = new Array(ln);
  for (var i = 0; i < ln; ++i) {
    result[i] = c_17212.charCodeAt(i);
  }
  return result;
  

	
}

function setConstr() {
		    var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_18230, src_18231, ti_18232) {
	var result_18419 = null;

		switch (ti_18232.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(is_fat_pointer_18201(ti_18232))) {
			result_18419 = src_18231;
			}
			else {
				result_18419 = [src_18231[0], src_18231[1]];
			}
			
			break;
		case 19:
			      if (dest_18230 === null || dest_18230 === undefined) {
        dest_18230 = {};
      }
      else {
        for (var key in dest_18230) { delete dest_18230[key]; }
      }
      for (var key in src_18231) { dest_18230[key] = src_18231[key]; }
      result_18419 = dest_18230;
    
			break;
		case 18:
		case 17:
			if (!((ti_18232.base == null))) {
			result_18419 = nimCopy(dest_18230, src_18231, ti_18232.base);
			}
			else {
			if ((ti_18232.kind == 17)) {
			result_18419 = (dest_18230 === null || dest_18230 === undefined) ? {m_type: ti_18232} : dest_18230;
			}
			else {
				result_18419 = (dest_18230 === null || dest_18230 === undefined) ? {} : dest_18230;
			}
			}
			nimCopyAux(result_18419, src_18231, ti_18232.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_18231 === null) {
        result_18419 = null;
      }
      else {
        if (dest_18230 === null || dest_18230 === undefined) {
          dest_18230 = new Array(src_18231.length);
        }
        else {
          dest_18230.length = src_18231.length;
        }
        result_18419 = dest_18230;
        for (var i = 0; i < src_18231.length; ++i) {
          result_18419[i] = nimCopy(result_18419[i], src_18231[i], ti_18232.base);
        }
      }
    
			break;
		case 28:
			      if (src_18231 !== null) {
        result_18419 = src_18231.slice(0);
      }
    
			break;
		default: 
			result_18419 = src_18231;
			break;
		}

	return result_18419;

}

function arrayConstr(len_18480, value_18481, typ_18482) {
		    var result = new Array(len_18480);
    for (var i = 0; i < len_18480; ++i) result[i] = nimCopy(null, value_18481, typ_18482);
    return result;
  

	
}

function cstrToNimstr(c_17229) {
		  var ln = c_17229.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_17229.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_17229.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

	
}

function toJSStr(s_17246) {
		  if (s_17246 === null) return "";
  var len = s_17246.length;
  var asciiPart = new Array(len);
  var fcc = String.fromCharCode;
  var nonAsciiPart = null;
  var nonAsciiOffset = 0;
  for (var i = 0; i < len; ++i) {
    if (nonAsciiPart !== null) {
      var offset = (i - nonAsciiOffset) * 2;
      var code = s_17246[i].toString(16);
      if (code.length == 1) {
        code = "0"+code;
      }
      nonAsciiPart[offset] = "%";
      nonAsciiPart[offset + 1] = code;
    }
    else if (s_17246[i] < 128)
      asciiPart[i] = fcc(s_17246[i]);
    else {
      asciiPart.length = i;
      nonAsciiOffset = i;
      nonAsciiPart = new Array((len - i) * 2);
      --i;
    }
  }
  asciiPart = asciiPart.join("");
  return (nonAsciiPart === null) ?
      asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}

function raiseException(e_16818, ename_16819) {
		e_16818.name = ename_16819;
		if ((excHandler == 0)) {
		unhandledException(e_16818);
		}
		
		e_16818.trace = nimCopy(null, raw_write_stack_trace_16641(), NTI138);
		throw e_16818;

	
}

function addInt(a_17603, b_17604) {
		    var result = a_17603 + b_17604;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}

function chckIndx(i_18499, a_18500, b_18501) {
			var Tmp1;

	var result_18502 = 0;

	BeforeRet: do {
			if (!(a_18500 <= i_18499)) Tmp1 = false; else {				Tmp1 = (i_18499 <= b_18501);			}		if (Tmp1) {
		result_18502 = i_18499;
		break BeforeRet;
		}
		else {
		raiseIndexError();
		}
		
	} while (false);

	return result_18502;

}

function subInt(a_17621, b_17622) {
		    var result = a_17621 - b_17622;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet2 = setConstr([65, 90]);

function chckRange(i_18518, a_18519, b_18520) {
			var Tmp1;

	var result_18521 = 0;

	BeforeRet: do {
			if (!(a_18519 <= i_18518)) Tmp1 = false; else {				Tmp1 = (i_18518 <= b_18520);			}		if (Tmp1) {
		result_18521 = i_18518;
		break BeforeRet;
		}
		else {
		raiseRangeError();
		}
		
	} while (false);

	return result_18521;

}
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_17639, b_17640) {
		    var result = a_17639 * b_17640;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

	
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);

function nimMax(a_17958, b_17959) {
		var Tmp1;

	var result_17960 = 0;

	BeforeRet: do {
		if ((b_17959 <= a_17958)) {
		Tmp1 = a_17958;
		}
		else {
		Tmp1 = b_17959;
		}
		
		result_17960 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_17960;

}

function nimMin(a_17940, b_17941) {
		var Tmp1;

	var result_17942 = 0;

	BeforeRet: do {
		if ((a_17940 <= b_17941)) {
		Tmp1 = a_17940;
		}
		else {
		Tmp1 = b_17941;
		}
		
		result_17942 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_17942;

}
var nimvm_7789 = false;
var nim_program_result = 0;
var global_raise_hook_14418 = [null];
var local_raise_hook_14423 = [null];
var out_of_mem_hook_14426 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var dorender_28091 = [null];
var draw_timeout_28092 = [null];
var current_tree_28093 = [null];
var link_counter_28542 = [0];
var radio_counter_29028 = [0];
var alternative_148499 = [null];

function is_fat_pointer_18201(ti_18203) {
	var result_18204 = false;

	BeforeRet: do {
		result_18204 = !((ConstSet1[ti_18203.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_18204;

}

function nimCopyAux(dest_18235, src_18236, n_18238) {
		switch (n_18238.kind) {
		case 0:
			break;
		case 1:
			      dest_18235[n_18238.offset] = nimCopy(dest_18235[n_18238.offset], src_18236[n_18238.offset], n_18238.typ);
    
			break;
		case 2:
			    for (var i = 0; i < n_18238.sons.length; i++) {
      nimCopyAux(dest_18235, src_18236, n_18238.sons[i]);
    }
    
			break;
		case 3:
			      dest_18235[n_18238.offset] = nimCopy(dest_18235[n_18238.offset], src_18236[n_18238.offset], n_18238.typ);
      for (var i = 0; i < n_18238.sons.length; ++i) {
        nimCopyAux(dest_18235, src_18236, n_18238.sons[i][1]);
      }
    
			break;
		}

	
}

function add_14438(x_14441, x_14441_Idx, y_14442) {
		      if (x_14441[x_14441_Idx] === null) { x_14441[x_14441_Idx] = []; }
      var off = x_14441[x_14441_Idx].length;
      x_14441[x_14441_Idx].length += y_14442.length;
      for (var i = 0; i < y_14442.length; ++i) {
        x_14441[x_14441_Idx][off+i] = y_14442.charCodeAt(i);
      }
    

	
}

function aux_write_stack_trace_16339(f_16341) {
					var Tmp3;

	var result_16342 = [null];

		var it_16350 = f_16341;
		var i_16352 = 0;
		var total_16354 = 0;
		var temp_frames_16361 = arrayConstr(64, {Field0: null, Field1: 0}, NTI16344);
		L1: do {
				L2: while (true) {
					if (!!((it_16350 == null))) Tmp3 = false; else {						Tmp3 = (i_16352 <= 63);					}				if (!Tmp3) break L2;
					temp_frames_16361[i_16352].Field0 = it_16350.procname;
					temp_frames_16361[i_16352].Field1 = it_16350.line;
					i_16352 += 1;
					total_16354 += 1;
					it_16350 = it_16350.prev;
				}
		} while(false);
		L4: do {
				L5: while (true) {
				if (!!((it_16350 == null))) break L5;
					total_16354 += 1;
					it_16350 = it_16350.prev;
				}
		} while(false);
		result_16342[0] = nimCopy(null, [], NTI138);
		if (!((total_16354 == i_16352))) {
		if (result_16342[0] != null) { result_16342[0] = (result_16342[0]).concat(makeNimstrLit("(")); } else { result_16342[0] = makeNimstrLit("("); };
		if (result_16342[0] != null) { result_16342[0] = (result_16342[0]).concat(cstrToNimstr(((total_16354 - i_16352))+"")); } else { result_16342[0] = cstrToNimstr(((total_16354 - i_16352))+"").slice(); };
		if (result_16342[0] != null) { result_16342[0] = (result_16342[0]).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_16342[0] = makeNimstrLit(" calls omitted) ...\x0A"); };
		}
		
		L6: do {
			var j_16624 = 0;
			var colontmp__148652 = 0;
			colontmp__148652 = (i_16352 - 1);
			var res_148658 = colontmp__148652;
			L7: do {
					L8: while (true) {
					if (!(0 <= res_148658)) break L8;
						j_16624 = res_148658;
						add_14438(result_16342, 0, temp_frames_16361[j_16624].Field0);
						if ((0 < temp_frames_16361[j_16624].Field1)) {
						if (result_16342[0] != null) { result_16342[0] = (result_16342[0]).concat(makeNimstrLit(", line: ")); } else { result_16342[0] = makeNimstrLit(", line: "); };
						if (result_16342[0] != null) { result_16342[0] = (result_16342[0]).concat(cstrToNimstr((temp_frames_16361[j_16624].Field1)+"")); } else { result_16342[0] = cstrToNimstr((temp_frames_16361[j_16624].Field1)+"").slice(); };
						}
						
						if (result_16342[0] != null) { result_16342[0] = (result_16342[0]).concat(makeNimstrLit("\x0A")); } else { result_16342[0] = makeNimstrLit("\x0A"); };
						res_148658 -= 1;
					}
			} while(false);
		} while(false);

	return result_16342[0];

}

function raw_write_stack_trace_16641() {
	var result_16643 = null;

		if (!((framePtr == null))) {
		result_16643 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A") || []).concat(aux_write_stack_trace_16339(framePtr) || []), NTI138);
		}
		else {
			result_16643 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI138);
		}
		

	return result_16643;

}

function unhandledException(e_16705) {
		var buf_16706 = [[]];
		if (!(((e_16705.message != null ? e_16705.message.length : 0) == 0))) {
		if (buf_16706[0] != null) { buf_16706[0] = (buf_16706[0]).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_16706[0] = makeNimstrLit("Error: unhandled exception: "); };
		if (buf_16706[0] != null) { buf_16706[0] = (buf_16706[0]).concat(e_16705.message); } else { buf_16706[0] = e_16705.message.slice(); };
		}
		else {
		if (buf_16706[0] != null) { buf_16706[0] = (buf_16706[0]).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_16706[0] = makeNimstrLit("Error: unhandled exception"); };
		}
		
		if (buf_16706[0] != null) { buf_16706[0] = (buf_16706[0]).concat(makeNimstrLit(" [")); } else { buf_16706[0] = makeNimstrLit(" ["); };
		add_14438(buf_16706, 0, e_16705.name);
		if (buf_16706[0] != null) { buf_16706[0] = (buf_16706[0]).concat(makeNimstrLit("]\x0A")); } else { buf_16706[0] = makeNimstrLit("]\x0A"); };
		if (buf_16706[0] != null) { buf_16706[0] = (buf_16706[0]).concat(raw_write_stack_trace_16641()); } else { buf_16706[0] = raw_write_stack_trace_16641().slice(); };
		var cbuf_16801 = toJSStr(buf_16706[0]);
		framePtr = null;
		  if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_16801);
  }
  else {
    throw cbuf_16801;
  }
  

	
}

function raiseOverflow() {
		var e_17059 = null;
		e_17059 = {m_type: NTI4246, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_17059.message = nimCopy(null, makeNimstrLit("over- or underflow"), NTI138);
		e_17059.parent = null;
		raiseException(e_17059, "OverflowError");

	
}

function is_whitespace_147642(text_147644) {
		     return !/[^\s]/.test(text_147644);
  

	
}

function is_whitespace_147659(x_147661) {
		var Tmp1;
		var Tmp2;

	var result_147662 = false;

	var F={procname:"dochack.isWhitespace",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 102;
		if (!(x_147661.nodeName == "#text")) Tmp2 = false; else {			Tmp2 = is_whitespace_147642(x_147661.textContent);		}		if (Tmp2) Tmp1 = true; else {			Tmp1 = (x_147661.nodeName == "#comment");		}		result_147662 = Tmp1;
	framePtr = F.prev;

	return result_147662;

}

function raiseIndexError() {
		var e_17143 = null;
		e_17143 = {m_type: NTI4258, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_17143.message = nimCopy(null, makeNimstrLit("index out of bounds"), NTI138);
		e_17143.parent = null;
		raiseException(e_17143, "IndexError");

	
}

function to_toc_147676(x_147678, father_147679) {
						var Tmp5;
						var Tmp6;
						var Tmp7;
			var Tmp14;

	var F={procname:"dochack.toToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if ((x_147678.nodeName == "UL")) {
		F.line = 107;
		var f_147702 = {heading: null, kids: [], sortId: (father_147679.kids != null ? father_147679.kids.length : 0), doSort: false};
		F.line = 108;
		var i_147704 = 0;
		L1: do {
			F.line = 109;
				L2: while (true) {
				if (!(i_147704 < x_147678.childNodes.length)) break L2;
					F.line = 110;
					var nxt_147705 = addInt(i_147704, 1);
					L3: do {
						F.line = 111;
							L4: while (true) {
							if (!((nxt_147705 < x_147678.childNodes.length) && is_whitespace_147659(x_147678.childNodes[nxt_147705]))) break L4;
								F.line = 112;
								nxt_147705 = addInt(nxt_147705, 1);
							}
					} while(false);
						if (!(nxt_147705 < x_147678.childNodes.length)) Tmp7 = false; else {							Tmp7 = (x_147678.childNodes[i_147704].nodeName == "LI");						}						if (!Tmp7) Tmp6 = false; else {							Tmp6 = (x_147678.childNodes[i_147704].childNodes.length == 1);						}						if (!Tmp6) Tmp5 = false; else {							Tmp5 = (x_147678.childNodes[nxt_147705].nodeName == "UL");						}					if (Tmp5) {
					F.line = 115;
					var e_147737 = {heading: x_147678.childNodes[i_147704].childNodes[0], kids: [], sortId: (f_147702.kids != null ? f_147702.kids.length : 0), doSort: false};
					F.line = 116;
					var it_147738 = x_147678.childNodes[nxt_147705];
					L8: do {
						F.line = 117;
						var j_147748 = 0;
						F.line = 3667;
						var colontmp__148624 = 0;
						F.line = 117;
						colontmp__148624 = it_147738.childNodes.length;
						F.line = 3668;
						var i_148626 = 0;
						L9: do {
							F.line = 3669;
								L10: while (true) {
								if (!(i_148626 < colontmp__148624)) break L10;
									F.line = 3670;
									j_147748 = i_148626;
									F.line = 118;
									to_toc_147676(it_147738.childNodes[j_147748], e_147737);
									F.line = 3671;
									i_148626 = addInt(i_148626, 1);
								}
						} while(false);
					} while(false);
					F.line = 119;
					if (f_147702.kids != null) { f_147702.kids.push(e_147737); } else { f_147702.kids = [e_147737]; };
					F.line = 120;
					i_147704 = addInt(nxt_147705, 1);
					}
					else {
						F.line = 122;
						to_toc_147676(x_147678.childNodes[i_147704], f_147702);
						F.line = 123;
						i_147704 = addInt(i_147704, 1);
					}
					
				}
		} while(false);
		F.line = 124;
		if (father_147679.kids != null) { father_147679.kids.push(f_147702); } else { father_147679.kids = [f_147702]; };
		}
		else {
		if (is_whitespace_147659(x_147678)) {
		}
		else {
		if ((x_147678.nodeName == "LI")) {
		F.line = 128;
		var idx_147794 = [];
		L11: do {
			F.line = 129;
			var i_147804 = 0;
			F.line = 3667;
			var colontmp__148630 = 0;
			F.line = 129;
			colontmp__148630 = x_147678.childNodes.length;
			F.line = 3668;
			var i_148632 = 0;
			L12: do {
				F.line = 3669;
					L13: while (true) {
					if (!(i_148632 < colontmp__148630)) break L13;
						F.line = 3670;
						i_147804 = i_148632;
						if (!(is_whitespace_147659(x_147678.childNodes[i_147804]))) {
						F.line = 130;
						if (idx_147794 != null) { idx_147794.push(i_147804); } else { idx_147794 = [i_147804]; };
						}
						
						F.line = 3671;
						i_148632 = addInt(i_148632, 1);
					}
			} while(false);
		} while(false);
			if (!((idx_147794 != null ? idx_147794.length : 0) == 2)) Tmp14 = false; else {				Tmp14 = (x_147678.childNodes[idx_147794[chckIndx(1, 0, idx_147794.length+0-1)-0]].nodeName == "UL");			}		if (Tmp14) {
		F.line = 132;
		var e_147844 = {heading: x_147678.childNodes[idx_147794[chckIndx(0, 0, idx_147794.length+0-1)-0]], kids: [], sortId: (father_147679.kids != null ? father_147679.kids.length : 0), doSort: false};
		F.line = 134;
		var it_147845 = x_147678.childNodes[idx_147794[chckIndx(1, 0, idx_147794.length+0-1)-0]];
		L15: do {
			F.line = 135;
			var j_147855 = 0;
			F.line = 3667;
			var colontmp__148637 = 0;
			F.line = 135;
			colontmp__148637 = it_147845.childNodes.length;
			F.line = 3668;
			var i_148639 = 0;
			L16: do {
				F.line = 3669;
					L17: while (true) {
					if (!(i_148639 < colontmp__148637)) break L17;
						F.line = 3670;
						j_147855 = i_148639;
						F.line = 136;
						to_toc_147676(it_147845.childNodes[j_147855], e_147844);
						F.line = 3671;
						i_148639 = addInt(i_148639, 1);
					}
			} while(false);
		} while(false);
		F.line = 137;
		if (father_147679.kids != null) { father_147679.kids.push(e_147844); } else { father_147679.kids = [e_147844]; };
		}
		else {
			L18: do {
				F.line = 139;
				var i_147875 = 0;
				F.line = 3667;
				var colontmp__148643 = 0;
				F.line = 139;
				colontmp__148643 = x_147678.childNodes.length;
				F.line = 3668;
				var i_148645 = 0;
				L19: do {
					F.line = 3669;
						L20: while (true) {
						if (!(i_148645 < colontmp__148643)) break L20;
							F.line = 3670;
							i_147875 = i_148645;
							F.line = 140;
							to_toc_147676(x_147678.childNodes[i_147875], father_147679);
							F.line = 3671;
							i_148645 = addInt(i_148645, 1);
						}
				} while(false);
			} while(false);
		}
		
		}
		else {
			F.line = 142;
		if (father_147679.kids != null) { father_147679.kids.push({heading: x_147678, kids: [], sortId: (father_147679.kids != null ? father_147679.kids.length : 0), doSort: false}); } else { father_147679.kids = [{heading: x_147678, kids: [], sortId: (father_147679.kids != null ? father_147679.kids.length : 0), doSort: false}]; };
		}
		}}
	framePtr = F.prev;

	
}

function extract_items_147179(x_147181, heading_147182, items_147185, items_147185_Idx) {
			var Tmp1;

	var F={procname:"dochack.extractItems",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_147181 == null)) {
		F.line = 49;
		break BeforeRet;
		}
		
			if (!!((x_147181.heading == null))) Tmp1 = false; else {				Tmp1 = (x_147181.heading.textContent == heading_147182);			}		if (Tmp1) {
		L2: do {
			F.line = 51;
			var i_147224 = 0;
			F.line = 3667;
			var colontmp__148664 = 0;
			F.line = 51;
			colontmp__148664 = (x_147181.kids != null ? x_147181.kids.length : 0);
			F.line = 3668;
			var i_148666 = 0;
			L3: do {
				F.line = 3669;
					L4: while (true) {
					if (!(i_148666 < colontmp__148664)) break L4;
						F.line = 3670;
						i_147224 = i_148666;
						F.line = 52;
						if (items_147185[items_147185_Idx] != null) { items_147185[items_147185_Idx].push(x_147181.kids[chckIndx(i_147224, 0, x_147181.kids.length+0-1)-0].heading); } else { items_147185[items_147185_Idx] = [x_147181.kids[chckIndx(i_147224, 0, x_147181.kids.length+0-1)-0].heading]; };
						F.line = 3671;
						i_148666 = addInt(i_148666, 1);
					}
			} while(false);
		} while(false);
		}
		else {
			L5: do {
				F.line = 54;
				var i_147251 = 0;
				F.line = 3667;
				var colontmp__148670 = 0;
				F.line = 54;
				colontmp__148670 = (x_147181.kids != null ? x_147181.kids.length : 0);
				F.line = 3668;
				var i_148672 = 0;
				L6: do {
					F.line = 3669;
						L7: while (true) {
						if (!(i_148672 < colontmp__148670)) break L7;
							F.line = 3670;
							i_147251 = i_148672;
							F.line = 55;
							var it_147252 = x_147181.kids[chckIndx(i_147251, 0, x_147181.kids.length+0-1)-0];
							F.line = 56;
							extract_items_147179(it_147252, heading_147182, items_147185, items_147185_Idx);
							F.line = 3671;
							i_148672 = addInt(i_148672, 1);
						}
				} while(false);
			} while(false);
		}
		
	} while (false);
	framePtr = F.prev;

	
}

function tree_28349(tag_28351, kids_28353) {
	var result_28354 = null;

	var F={procname:"karax.tree",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 103;
		result_28354 = document.createElement(toJSStr(tag_28351));
		L1: do {
			F.line = 104;
			var k_28392 = null;
			F.line = 2284;
			var i_148694 = 0;
			L2: do {
				F.line = 2285;
					L3: while (true) {
					if (!(i_148694 < (kids_28353 != null ? kids_28353.length : 0))) break L3;
						F.line = 2286;
						k_28392 = kids_28353[chckIndx(i_148694, 0, kids_28353.length+0-1)-0];
						F.line = 105;
						result_28354.appendChild(k_28392);
						F.line = 2287;
						i_148694 = addInt(i_148694, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	return result_28354;

}

function text_28483(s_28485) {
	var result_28486 = null;

	var F={procname:"karax.text",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 113;
		result_28486 = document.createTextNode(s_28485);
	framePtr = F.prev;

	return result_28486;

}

function set_attr_29304(e_29306, key_29307, value_29308) {
	var F={procname:"karax.setAttr",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 273;
		e_29306.setAttribute(key_29307, value_29308);
	framePtr = F.prev;

	
}

function sys_fatal_21437(message_21443) {
	var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"../../lib/system.nim",line:0};
	framePtr = F;
		F.line = 2966;
		var e_21445 = null;
		F.line = 2967;
		e_21445 = {m_type: NTI4250, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		F.line = 2968;
		e_21445.message = nimCopy(null, message_21443, NTI138);
		F.line = 2969;
		raiseException(e_21445, "AssertionError");
	framePtr = F.prev;

	
}

function raise_assert_21432(msg_21434) {
	var F={procname:"system.raiseAssert",prev:framePtr,filename:"../../lib/system.nim",line:0};
	framePtr = F;
		F.line = 3923;
		sys_fatal_21437(msg_21434);
	framePtr = F.prev;

	
}

function failed_assert_impl_21480(msg_21482) {
	var F={procname:"system.failedAssertImpl",prev:framePtr,filename:"../../lib/system.nim",line:0};
	framePtr = F;
		F.line = 3930;
		raise_assert_21432(msg_21482);
	framePtr = F.prev;

	
}

function uncovered_147982(x_147984) {
			var Tmp1;
		var Tmp2;

	var result_147985 = null;

	var F={procname:"dochack.uncovered",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
			if (!((x_147984.kids != null ? x_147984.kids.length : 0) == 0)) Tmp1 = false; else {				Tmp1 = !((x_147984.heading == null));			}		if (Tmp1) {
		F.line = 162;
		if (!(x_147984.heading.hasOwnProperty('__karaxMarker__'))) {
		Tmp2 = x_147984;
		}
		else {
		Tmp2 = null;
		}
		
		result_147985 = Tmp2;
		break BeforeRet;
		}
		
		F.line = 163;
		result_147985 = {heading: x_147984.heading, kids: [], sortId: x_147984.sortId, doSort: x_147984.doSort};
		L3: do {
			F.line = 165;
			var i_148035 = 0;
			F.line = 3667;
			var colontmp__148707 = 0;
			F.line = 165;
			colontmp__148707 = (x_147984.kids != null ? x_147984.kids.length : 0);
			F.line = 3668;
			var i_148709 = 0;
			L4: do {
				F.line = 3669;
					L5: while (true) {
					if (!(i_148709 < colontmp__148707)) break L5;
						F.line = 3670;
						i_148035 = i_148709;
						F.line = 166;
						var y_148036 = uncovered_147982(x_147984.kids[chckIndx(i_148035, 0, x_147984.kids.length+0-1)-0]);
						if (!((y_148036 == null))) {
						F.line = 167;
						if (result_147985.kids != null) { result_147985.kids.push(y_148036); } else { result_147985.kids = [y_148036]; };
						}
						
						F.line = 3671;
						i_148709 = addInt(i_148709, 1);
					}
			} while(false);
		} while(false);
		if (((result_147985.kids != null ? result_147985.kids.length : 0) == 0)) {
		F.line = 168;
		result_147985 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_147985;

}

function merge_tocs_148078(orig_148080, news_148081) {
	var result_148082 = null;

	var F={procname:"dochack.mergeTocs",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 171;
		result_148082 = uncovered_147982(orig_148080);
		if ((result_148082 == null)) {
		F.line = 173;
		result_148082 = news_148081;
		}
		else {
			L1: do {
				F.line = 175;
				var i_148110 = 0;
				F.line = 3667;
				var colontmp__148700 = 0;
				F.line = 175;
				colontmp__148700 = (news_148081.kids != null ? news_148081.kids.length : 0);
				F.line = 3668;
				var i_148702 = 0;
				L2: do {
					F.line = 3669;
						L3: while (true) {
						if (!(i_148702 < colontmp__148700)) break L3;
							F.line = 3670;
							i_148110 = i_148702;
							F.line = 176;
							if (result_148082.kids != null) { result_148082.kids.push(news_148081.kids[chckIndx(i_148110, 0, news_148081.kids.length+0-1)-0]); } else { result_148082.kids = [news_148081.kids[chckIndx(i_148110, 0, news_148081.kids.length+0-1)-0]]; };
							F.line = 3671;
							i_148702 = addInt(i_148702, 1);
						}
				} while(false);
			} while(false);
		}
		
	framePtr = F.prev;

	return result_148082;

}

function build_toc_148134(orig_148136, types_148138, procs_148139) {
	var result_148140 = null;

	var F={procname:"dochack.buildToc",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 179;
		var new_stuff_148156 = {heading: null, kids: [], doSort: true, sortId: 0};
		L1: do {
			F.line = 180;
			var t_148414 = null;
			F.line = 3964;
			var i_148687 = 0;
			F.line = 3965;
			var l_148689 = (types_148138 != null ? types_148138.length : 0);
			L2: do {
				F.line = 3966;
					L3: while (true) {
					if (!(i_148687 < l_148689)) break L3;
						F.line = 3967;
						t_148414 = types_148138[chckIndx(i_148687, 0, types_148138.length+0-1)-0];
						F.line = 181;
						var c_148430 = {heading: t_148414.cloneNode(true), kids: [], doSort: true, sortId: 0};
						F.line = 182;
						t_148414.__karaxMarker__ = true;
						L4: do {
							F.line = 183;
							var p_148439 = null;
							F.line = 3964;
							var i_148682 = 0;
							F.line = 3965;
							var l_148684 = (procs_148139 != null ? procs_148139.length : 0);
							L5: do {
								F.line = 3966;
									L6: while (true) {
									if (!(i_148682 < l_148684)) break L6;
										F.line = 3967;
										p_148439 = procs_148139[chckIndx(i_148682, 0, procs_148139.length+0-1)-0];
										if (!(p_148439.hasOwnProperty('__karaxMarker__'))) {
										F.line = 185;
										var xx_148440 = p_148439.parentNode.getElementsByClassName("attachedType");
										if ((((xx_148440 != null ? xx_148440.length : 0) == 1) && (xx_148440[chckIndx(0, 0, xx_148440.length+0-1)-0].textContent == t_148414.textContent))) {
										F.line = 188;
										var q_148450 = tree_28349(makeNimstrLit("A"), [text_28483(p_148439.title)]);
										F.line = 189;
										set_attr_29304(q_148450, "href", p_148439.getAttribute("href"));
										F.line = 190;
										if (c_148430.kids != null) { c_148430.kids.push({heading: q_148450, kids: [], sortId: 0, doSort: false}); } else { c_148430.kids = [{heading: q_148450, kids: [], sortId: 0, doSort: false}]; };
										F.line = 191;
										p_148439.__karaxMarker__ = true;
										}
										
										}
										
										F.line = 3968;
										i_148682 = addInt(i_148682, 1);
										if (!(((procs_148139 != null ? procs_148139.length : 0) == l_148684))) {
										F.line = 3969;
										failed_assert_impl_21480(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3969, 11) `len(a) == L` seq modified while iterating over it"));
										}
										
									}
							} while(false);
						} while(false);
						F.line = 192;
						if (new_stuff_148156.kids != null) { new_stuff_148156.kids.push(c_148430); } else { new_stuff_148156.kids = [c_148430]; };
						F.line = 3968;
						i_148687 = addInt(i_148687, 1);
						if (!(((types_148138 != null ? types_148138.length : 0) == l_148689))) {
						F.line = 3969;
						failed_assert_impl_21480(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3969, 11) `len(a) == L` seq modified while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		F.line = 193;
		result_148140 = merge_tocs_148078(orig_148136, new_stuff_148156);
	framePtr = F.prev;

	return result_148140;

}

function add_28500(parent_28502, kid_28503) {
			var Tmp1;
				var Tmp2;

	var F={procname:"karax.add",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
			if (!(parent_28502.nodeName == "TR")) Tmp1 = false; else {				if ((kid_28503.nodeName == "TD")) Tmp2 = true; else {					Tmp2 = (kid_28503.nodeName == "TH");				}				Tmp1 = Tmp2;			}		if (Tmp1) {
		F.line = 117;
		var k_28504 = document.createElement("TD");
		F.line = 118;
		k_28504.appendChild(kid_28503);
		F.line = 119;
		parent_28502.appendChild(k_28504);
		}
		else {
			F.line = 121;
		parent_28502.appendChild(kid_28503);
		}
		
	framePtr = F.prev;

	
}

function set_class_29287(e_29289, value_29290) {
	var F={procname:"karax.setClass",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 270;
		e_29289.setAttribute("class", toJSStr(value_29290));
	framePtr = F.prev;

	
}

function to_html_147266(x_147268, is_root_147269) {
			var Tmp1;

		function HEX3Aanonymous_147320(a_147322, b_147323) {
					var Tmp1;

			var result_147324 = 0;

			var F={procname:"toHtml.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
			BeforeRet: do {
					if (!!((a_147322.heading == null))) Tmp1 = false; else {						Tmp1 = !((b_147323.heading == null));					}				if (Tmp1) {
				F.line = 74;
				var x_147347 = a_147322.heading.textContent;
				F.line = 75;
				var y_147348 = b_147323.heading.textContent;
				if ((x_147347 < y_147348)) {
				F.line = 76;
				result_147324 = -1;
				break BeforeRet;
				}
				
				if ((y_147348 < x_147347)) {
				F.line = 77;
				result_147324 = 1;
				break BeforeRet;
				}
				
				F.line = 78;
				result_147324 = 0;
				break BeforeRet;
				}
				else {
					F.line = 81;
					result_147324 = subInt(a_147322.sortId, b_147323.sortId);
					break BeforeRet;
				}
				
			} while (false);
			framePtr = F.prev;

			return result_147324;

		}

	var result_147270 = null;

	var F={procname:"dochack.toHtml",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((x_147268 == null)) {
		F.line = 59;
		result_147270 = null;
		break BeforeRet;
		}
		
		if (((x_147268.kids != null ? x_147268.kids.length : 0) == 0)) {
		if ((x_147268.heading == null)) {
		F.line = 61;
		result_147270 = null;
		break BeforeRet;
		}
		
		F.line = 62;
		result_147270 = x_147268.heading.cloneNode(true);
		break BeforeRet;
		}
		
		F.line = 63;
		result_147270 = tree_28349(makeNimstrLit("DIV"), []);
			if (!!((x_147268.heading == null))) Tmp1 = false; else {				Tmp1 = !(x_147268.heading.hasOwnProperty('__karaxMarker__'));			}		if (Tmp1) {
		F.line = 65;
		add_28500(result_147270, x_147268.heading.cloneNode(true));
		}
		
		F.line = 66;
		var ul_147317 = tree_28349(makeNimstrLit("UL"), []);
		if (is_root_147269) {
		F.line = 68;
		set_class_29287(ul_147317, makeNimstrLit("simple simple-toc"));
		}
		else {
			F.line = 70;
		set_class_29287(ul_147317, makeNimstrLit("simple"));
		}
		
		if (x_147268.doSort) {
		F.line = 72;
		x_147268.kids.sort(HEX3Aanonymous_147320);
		}
		
		L2: do {
			F.line = 83;
			var k_147614 = null;
			F.line = 3962;
			var colontmp__148715 = null;
			F.line = 83;
			colontmp__148715 = x_147268.kids;
			F.line = 3964;
			var i_148718 = 0;
			F.line = 3965;
			var l_148720 = (colontmp__148715 != null ? colontmp__148715.length : 0);
			L3: do {
				F.line = 3966;
					L4: while (true) {
					if (!(i_148718 < l_148720)) break L4;
						F.line = 3967;
						k_147614 = colontmp__148715[chckIndx(i_148718, 0, colontmp__148715.length+0-1)-0];
						F.line = 84;
						var y_147615 = to_html_147266(k_147614, false);
						if (!((y_147615 == null))) {
						F.line = 86;
						add_28500(ul_147317, tree_28349(makeNimstrLit("LI"), [y_147615]));
						}
						
						F.line = 3968;
						i_148718 = addInt(i_148718, 1);
						if (!(((colontmp__148715 != null ? colontmp__148715.length : 0) == l_148720))) {
						F.line = 3969;
						failed_assert_impl_21480(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3969, 11) `len(a) == L` seq modified while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		if (!((ul_147317.childNodes.length == 0))) {
		F.line = 87;
		add_28500(result_147270, ul_147317);
		}
		
		if ((result_147270.childNodes.length == 0)) {
		F.line = 88;
		result_147270 = null;
		}
		
	} while (false);
	framePtr = F.prev;

	return result_147270;

}

function replace_by_id_28161(id_28163, new_tree_28164) {
	var F={procname:"karax.replaceById",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 54;
		var x_28165 = document.getElementById(id_28163);
		F.line = 55;
		x_28165.parentNode.replaceChild(new_tree_28164, x_28165);
		F.line = 56;
		new_tree_28164.id = id_28163;
	framePtr = F.prev;

	
}

function togglevis_148513(d_148515) {
	var F={procname:"dochack.togglevis",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 198;
		    if (d_148515.style.display == 'none')
      d_148515.style.display = 'inline';
    else
      d_148515.style.display = 'none';
  
	framePtr = F.prev;

	
}

function groupBy(value_148531) {
	var F={procname:"dochack.groupBy",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		F.line = 206;
		var toc_148532 = document.getElementById("toc-list");
		if ((alternative_148499[0] === null)) {
		F.line = 208;
		var tt_148555 = {heading: null, kids: [], sortId: 0, doSort: false};
		F.line = 209;
		to_toc_147676(toc_148532, tt_148555);
		F.line = 210;
		tt_148555 = tt_148555.kids[chckIndx(0, 0, tt_148555.kids.length+0-1)-0];
		F.line = 212;
		var types_148572 = [[]];
		F.line = 213;
		var procs_148589 = [[]];
		F.line = 215;
		extract_items_147179(tt_148555, "Types", types_148572, 0);
		F.line = 216;
		extract_items_147179(tt_148555, "Procs", procs_148589, 0);
		F.line = 217;
		extract_items_147179(tt_148555, "Converters", procs_148589, 0);
		F.line = 218;
		extract_items_147179(tt_148555, "Methods", procs_148589, 0);
		F.line = 219;
		extract_items_147179(tt_148555, "Templates", procs_148589, 0);
		F.line = 220;
		extract_items_147179(tt_148555, "Macros", procs_148589, 0);
		F.line = 221;
		extract_items_147179(tt_148555, "Iterators", procs_148589, 0);
		F.line = 223;
		var ntoc_148597 = build_toc_148134(tt_148555, types_148572[0], procs_148589[0]);
		F.line = 224;
		var x_148598 = to_html_147266(ntoc_148597, true);
		F.line = 225;
		alternative_148499[0] = tree_28349(makeNimstrLit("DIV"), [x_148598]);
		}
		
		if ((value_148531 == "type")) {
		F.line = 227;
		replace_by_id_28161("tocRoot", alternative_148499[0]);
		}
		else {
			F.line = 229;
		replace_by_id_28161("tocRoot", tree_28349(makeNimstrLit("DIV"), []));
		}
		
		F.line = 230;
		togglevis_148513(document.getElementById("toc-list"));
	framePtr = F.prev;

	
}
var db_148723 = [null];
var contents_148725 = [null];
var oldtoc_148935 = [null];
var timer_148936 = [null];

function raiseRangeError() {
		var e_17115 = null;
		e_17115 = {m_type: NTI4262, parent: null, name: null, message: null, trace: null, raiseId: 0, up: null};
		e_17115.message = nimCopy(null, makeNimstrLit("value out of range"), NTI138);
		e_17115.parent = null;
		raiseException(e_17115, "RangeError");

	
}

function nsuToLowerAsciiChar(c_128157) {
	var result_128158 = 0;

	var F={procname:"strutils.toLowerAscii",prev:framePtr,filename:"../../lib/pure/strutils.nim",line:0};
	framePtr = F;
		if ((ConstSet2[c_128157] != undefined)) {
		F.line = 265;
		result_128158 = chckRange(addInt(c_128157, 32), 0, 255);
		}
		else {
			F.line = 267;
			result_128158 = c_128157;
		}
		
	framePtr = F.prev;

	return result_128158;

}

function fuzzy_match_146044(pattern_146046, str_146047) {
							var Tmp4;
							var Tmp5;
								var Tmp6;

	var result_146051 = {Field0: 0, Field1: false};

	var F={procname:"fuzzysearch.fuzzyMatch",prev:framePtr,filename:"fuzzysearch.nim",line:0};
	framePtr = F;
		F.line = 37;
		var score_state_146052 = -100;
		F.line = 38;
		var header_matched_146053 = false;
		F.line = 39;
		var unmatched_leading_char_count_146055 = 0;
		F.line = 40;
		var consecutive_match_count_146057 = 0;
		F.line = 41;
		var str_index_146059 = 0;
		F.line = 42;
		var pat_index_146061 = 0;
		F.line = 43;
		var score_146063 = 0;
		L1: do {
			F.line = 49;
				L2: while (true) {
				if (!((str_index_146059 < (str_146047 != null ? str_146047.length : 0)) && (pat_index_146061 < (pattern_146046 != null ? pattern_146046.length : 0)))) break L2;
					L3: do {
						F.line = 51;
						var pattern_char_146070 = nsuToLowerAsciiChar(pattern_146046.charCodeAt(chckIndx(pat_index_146061, 0, pattern_146046.length+0-1)-0));
						F.line = 52;
						var str_char_146071 = nsuToLowerAsciiChar(str_146047.charCodeAt(chckIndx(str_index_146059, 0, str_146047.length+0-1)-0));
						if ((ConstSet3[pattern_char_146070] != undefined)) {
						F.line = 56;
						pat_index_146061 = addInt(pat_index_146061, 1);
						F.line = 57;
						break L3;
						}
						
						if ((ConstSet4[str_char_146071] != undefined)) {
						F.line = 59;
						str_index_146059 = addInt(str_index_146059, 1);
						F.line = 60;
						break L3;
						}
						
						if ((!(header_matched_146053) && (str_char_146071 == 58))) {
						F.line = 65;
						header_matched_146053 = true;
						F.line = 66;
						score_state_146052 = -100;
						F.line = 67;
						score_146063 = Math.trunc(Math.floor((5.0000000000000000e-01 * score_146063)));
						F.line = 68;
						pat_index_146061 = 0;
						F.line = 69;
						str_index_146059 = addInt(str_index_146059, 1);
						F.line = 70;
						break L3;
						}
						
						if ((str_char_146071 == pattern_char_146070)) {
						F.line = 73;
						switch (score_state_146052) {
						case -100:
						case 20:
							F.line = 75;
							score_state_146052 = 10;
							break;
						case 0:
							F.line = 78;
							score_state_146052 = 5;
							F.line = 78;
							score_146063 = addInt(score_146063, score_state_146052);
							break;
						case 10:
						case 5:
							F.line = 81;
							consecutive_match_count_146057 = addInt(consecutive_match_count_146057, 1);
							F.line = 82;
							score_state_146052 = 5;
							F.line = 83;
							score_146063 = addInt(score_146063, mulInt(5, consecutive_match_count_146057));
							if ((score_state_146052 == 10)) {
							F.line = 86;
							score_146063 = addInt(score_146063, 10);
							}
							
							F.line = 88;
							var on_boundary_146182 = (pat_index_146061 == (pattern_146046 != null ? (pattern_146046.length-1) : -1));
							if ((!(on_boundary_146182) && (str_index_146059 < (str_146047 != null ? (str_146047.length-1) : -1)))) {
							F.line = 91;
							var next_pattern_char_146183 = nsuToLowerAsciiChar(pattern_146046.charCodeAt(chckIndx(addInt(pat_index_146061, 1), 0, pattern_146046.length+0-1)-0));
							F.line = 92;
							var next_str_char_146184 = nsuToLowerAsciiChar(str_146047.charCodeAt(chckIndx(addInt(str_index_146059, 1), 0, str_146047.length+0-1)-0));
							F.line = 95;
							if (!!((ConstSet5[next_str_char_146184] != undefined))) Tmp4 = false; else {								Tmp4 = !((next_str_char_146184 == next_pattern_char_146183));							}							on_boundary_146182 = Tmp4;
							}
							
							if (on_boundary_146182) {
							F.line = 100;
							score_state_146052 = 20;
							F.line = 100;
							score_146063 = addInt(score_146063, score_state_146052);
							}
							
							break;
						case -1:
						case -3:
							F.line = 103;
							if (!((ConstSet6[str_146047.charCodeAt(chckIndx(subInt(str_index_146059, 1), 0, str_146047.length+0-1)-0)] != undefined))) Tmp5 = true; else {								if (!(ConstSet7[str_146047.charCodeAt(chckIndx(subInt(str_index_146059, 1), 0, str_146047.length+0-1)-0)] != undefined)) Tmp6 = false; else {									Tmp6 = (ConstSet8[str_146047.charCodeAt(chckIndx(str_index_146059, 0, str_146047.length+0-1)-0)] != undefined);								}								Tmp5 = Tmp6;							}							var is_leading_char_146239 = Tmp5;
							if (is_leading_char_146239) {
							F.line = 110;
							score_state_146052 = 10;
							}
							else {
								F.line = 114;
								score_state_146052 = 0;
								F.line = 114;
								score_146063 = addInt(score_146063, score_state_146052);
							}
							
							break;
						}
						F.line = 115;
						pat_index_146061 = addInt(pat_index_146061, 1);
						}
						else {
							F.line = 118;
							switch (score_state_146052) {
							case -100:
								F.line = 120;
								score_state_146052 = -3;
								F.line = 120;
								score_146063 = addInt(score_146063, score_state_146052);
								break;
							case 5:
								F.line = 123;
								score_state_146052 = -1;
								F.line = 123;
								score_146063 = addInt(score_146063, score_state_146052);
								F.line = 124;
								consecutive_match_count_146057 = 0;
								break;
							case -3:
								if ((unmatched_leading_char_count_146055 < 3)) {
								F.line = 128;
								score_state_146052 = -3;
								F.line = 128;
								score_146063 = addInt(score_146063, score_state_146052);
								}
								
								F.line = 129;
								unmatched_leading_char_count_146055 = addInt(unmatched_leading_char_count_146055, 1);
								break;
							default: 
								F.line = 132;
								score_state_146052 = -1;
								F.line = 132;
								score_146063 = addInt(score_146063, score_state_146052);
								break;
							}
						}
						
						F.line = 134;
						str_index_146059 = addInt(str_index_146059, 1);
					} while(false);
				}
		} while(false);
		F.line = 136;
		nimCopy(result_146051, {Field0: nimMax(0, score_146063), Field1: (0 < score_146063)}, NTI146048);
	framePtr = F.prev;

	return result_146051;

}

function text_28466(s_28468) {
	var result_28469 = null;

	var F={procname:"karax.text",prev:framePtr,filename:"karax.nim",line:0};
	framePtr = F;
		F.line = 112;
		result_28469 = document.createTextNode(toJSStr(s_28468));
	framePtr = F.prev;

	return result_28469;

}

function dosearch_148743(value_148745) {

		function HEX3Aanonymous_148847(a_148857, b_148859) {
			var result_148865 = 0;

			var F={procname:"dosearch.:anonymous",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 274;
				result_148865 = subInt(b_148859["Field1"], a_148857["Field1"]);
			framePtr = F.prev;

			return result_148865;

		}

	var result_148746 = null;

	var F={procname:"dochack.dosearch",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (((db_148723[0] != null ? db_148723[0].length : 0) == 0)) {
		F.line = 240;
		var stuff_148754 = null;
		F.line = 241;
		    var request = new XMLHttpRequest();
    request.open("GET", "theindex.html", false);
    request.send(null);

    var doc = document.implementation.createHTMLDocument("theindex");
    doc.documentElement.innerHTML = request.responseText;

    //parser=new DOMParser();
    //doc=parser.parseFromString("<html></html>", "text/html");

    stuff_148754 = doc.documentElement;
    
		F.line = 254;
		db_148723[0] = nimCopy(null, stuff_148754.getElementsByClassName("reference"), NTI28057);
		F.line = 255;
		contents_148725[0] = nimCopy(null, [], NTI148769);
		L1: do {
			F.line = 256;
			var ahref_148778 = null;
			F.line = 3964;
			var i_149011 = 0;
			F.line = 3965;
			var l_149013 = (db_148723[0] != null ? db_148723[0].length : 0);
			L2: do {
				F.line = 3966;
					L3: while (true) {
					if (!(i_149011 < l_149013)) break L3;
						F.line = 3967;
						ahref_148778 = db_148723[0][chckIndx(i_149011, 0, db_148723[0].length+0-1)-0];
						F.line = 257;
						if (contents_148725[0] != null) { contents_148725[0].push(ahref_148778.getAttribute("data-doc-search-tag")); } else { contents_148725[0] = [ahref_148778.getAttribute("data-doc-search-tag")]; };
						F.line = 3968;
						i_149011 = addInt(i_149011, 1);
						if (!(((db_148723[0] != null ? db_148723[0].length : 0) == l_149013))) {
						F.line = 3969;
						failed_assert_impl_21480(makeNimstrLit("/Users/travis/build/nim-lang/Nim/lib/system.nim(3969, 11) `len(a) == L` seq modified while iterating over it"));
						}
						
					}
			} while(false);
		} while(false);
		}
		
		F.line = 258;
		var ul_148792 = tree_28349(makeNimstrLit("UL"), []);
		F.line = 259;
		result_148746 = tree_28349(makeNimstrLit("DIV"), []);
		F.line = 260;
		set_class_29287(result_148746, makeNimstrLit("search_results"));
		F.line = 261;
		var matches_148813 = [];
		L4: do {
			F.line = 262;
			var i_148830 = 0;
			F.line = 3667;
			var colontmp__149019 = 0;
			F.line = 262;
			colontmp__149019 = (db_148723[0] != null ? db_148723[0].length : 0);
			F.line = 3668;
			var i_149021 = 0;
			L5: do {
				F.line = 3669;
					L6: while (true) {
					if (!(i_149021 < colontmp__149019)) break L6;
						F.line = 3670;
						i_148830 = i_149021;
						L7: do {
							F.line = 263;
							var c_148831 = contents_148725[0][chckIndx(i_148830, 0, contents_148725[0].length+0-1)-0];
							if (((c_148831 == "Examples") || (c_148831 == "PEG construction"))) {
							F.line = 268;
							break L7;
							}
							
							F.line = 269;
							var colontmp__149030 = {Field0: 0, Field1: false};
							F.line = 269;
							var score_148832 = 0;
							F.line = 269;
							var matched_148833 = false;
							F.line = 269;
							nimCopy(colontmp__149030, fuzzy_match_146044(value_148745, c_148831), NTI146048);
							F.line = 269;
							score_148832 = colontmp__149030["Field0"];
							F.line = 269;
							matched_148833 = colontmp__149030["Field1"];
							if (matched_148833) {
							F.line = 271;
							if (matches_148813 != null) { matches_148813.push({Field0: db_148723[0][chckIndx(i_148830, 0, db_148723[0].length+0-1)-0], Field1: score_148832}); } else { matches_148813 = [{Field0: db_148723[0][chckIndx(i_148830, 0, db_148723[0].length+0-1)-0], Field1: score_148832}]; };
							}
							
						} while(false);
						F.line = 3671;
						i_149021 = addInt(i_149021, 1);
					}
			} while(false);
		} while(false);
		F.line = 273;
		matches_148813.sort(HEX3Aanonymous_148847);
		L8: do {
			F.line = 275;
			var i_148915 = 0;
			F.line = 3667;
			var colontmp__149025 = 0;
			F.line = 275;
			colontmp__149025 = nimMin((matches_148813 != null ? matches_148813.length : 0), 19);
			F.line = 3668;
			var i_149027 = 0;
			L9: do {
				F.line = 3669;
					L10: while (true) {
					if (!(i_149027 < colontmp__149025)) break L10;
						F.line = 3670;
						i_148915 = i_149027;
						F.line = 276;
						matches_148813[chckIndx(i_148915, 0, matches_148813.length+0-1)-0]["Field0"].innerHTML = matches_148813[chckIndx(i_148915, 0, matches_148813.length+0-1)-0]["Field0"].getAttribute("data-doc-search-tag");
						F.line = 277;
						add_28500(ul_148792, tree_28349(makeNimstrLit("LI"), [matches_148813[chckIndx(i_148915, 0, matches_148813.length+0-1)-0]["Field0"]]));
						F.line = 3671;
						i_149027 = addInt(i_149027, 1);
					}
			} while(false);
		} while(false);
		if ((ul_148792.childNodes.length == 0)) {
		F.line = 279;
		add_28500(result_148746, tree_28349(makeNimstrLit("B"), [text_28466(makeNimstrLit("no search results"))]));
		}
		else {
			F.line = 281;
			add_28500(result_148746, tree_28349(makeNimstrLit("B"), [text_28466(makeNimstrLit("search results"))]));
			F.line = 282;
			add_28500(result_148746, ul_148792);
		}
		
	framePtr = F.prev;

	return result_148746;

}

function search() {

		function wrapper_148952() {
			var F={procname:"search.wrapper",prev:framePtr,filename:"dochack.nim",line:0};
			framePtr = F;
				F.line = 289;
				var elem_148954 = document.getElementById("searchInput");
				F.line = 290;
				var value_148955 = elem_148954.value;
				if (!(((value_148955 != null ? value_148955.length : 0) == 0))) {
				if ((oldtoc_148935[0] === null)) {
				F.line = 293;
				oldtoc_148935[0] = document.getElementById("tocRoot");
				}
				
				F.line = 294;
				var results_148963 = dosearch_148743(value_148955);
				F.line = 295;
				replace_by_id_28161("tocRoot", results_148963);
				}
				else {
				if (!((oldtoc_148935[0] === null))) {
				F.line = 297;
				replace_by_id_28161("tocRoot", oldtoc_148935[0]);
				}
				}
			framePtr = F.prev;

			
		}

	var F={procname:"dochack.search",prev:framePtr,filename:"dochack.nim",line:0};
	framePtr = F;
		if (!((timer_148936[0] == null))) {
		F.line = 299;
		clearTimeout(timer_148936[0]);
		}
		
		F.line = 300;
		timer_148936[0] = setTimeout(wrapper_148952, 400);
	framePtr = F.prev;

	
}
